# Generated by Django 3.2 on 2024-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snackinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/snack'),
            preserve_default=False,
        ),
    ]
