# Generated by Django 3.2 on 2024-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240418_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackinfo',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snackinfo',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snackinfo',
            name='x_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
