# Generated by Django 3.2 on 2024-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240419_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackinfo',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='snackinfo',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='snackinfo',
            name='x_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
